
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.VBox vbox2;

	private global::Gtk.FileChooserWidget FileChooserWidget;

	private global::Gtk.ScrolledWindow scrolledwindow3;

	private global::Gtk.Image ImageView;

	private global::Gtk.HButtonBox hbuttonbox6;

	private global::Gtk.Button PrevBtn;

	private global::Gtk.Button NextBtn;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.Icon = global::Stetic.IconLoader.LoadIcon(this, "stock_fullscreen", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.FileChooserWidget = new global::Gtk.FileChooserWidget(((global::Gtk.FileChooserAction)(0)));
		this.FileChooserWidget.HeightRequest = 0;
		this.FileChooserWidget.Name = "FileChooserWidget";
		this.vbox2.Add(this.FileChooserWidget);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.FileChooserWidget]));
		w2.Position = 0;
		// Container child vbox2.Gtk.Box+BoxChild
		this.scrolledwindow3 = new global::Gtk.ScrolledWindow();
		this.scrolledwindow3.CanFocus = true;
		this.scrolledwindow3.Name = "scrolledwindow3";
		this.scrolledwindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow3.Gtk.Container+ContainerChild
		global::Gtk.Viewport w3 = new global::Gtk.Viewport();
		w3.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.ImageView = new global::Gtk.Image();
		this.ImageView.HeightRequest = 400;
		this.ImageView.Name = "ImageView";
		w3.Add(this.ImageView);
		this.scrolledwindow3.Add(w3);
		this.vbox2.Add(this.scrolledwindow3);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.scrolledwindow3]));
		w6.Position = 1;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbuttonbox6 = new global::Gtk.HButtonBox();
		this.hbuttonbox6.HeightRequest = 50;
		this.hbuttonbox6.Name = "hbuttonbox6";
		this.hbuttonbox6.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
		// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
		this.PrevBtn = new global::Gtk.Button();
		this.PrevBtn.CanFocus = true;
		this.PrevBtn.Name = "PrevBtn";
		this.PrevBtn.UseUnderline = true;
		this.PrevBtn.Label = global::Mono.Unix.Catalog.GetString("Prev");
		this.hbuttonbox6.Add(this.PrevBtn);
		global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6[this.PrevBtn]));
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
		this.NextBtn = new global::Gtk.Button();
		this.NextBtn.CanFocus = true;
		this.NextBtn.Name = "NextBtn";
		this.NextBtn.UseUnderline = true;
		this.NextBtn.Label = global::Mono.Unix.Catalog.GetString("Next");
		this.hbuttonbox6.Add(this.NextBtn);
		global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6[this.NextBtn]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		this.vbox2.Add(this.hbuttonbox6);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbuttonbox6]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		this.Add(this.vbox2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 1085;
		this.DefaultHeight = 823;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.FileChooserWidget.CurrentFolderChanged += new global::System.EventHandler(this.onFolderChanged);
		this.FileChooserWidget.SelectionChanged += new global::System.EventHandler(this.onFileSelected);
		this.PrevBtn.Clicked += new global::System.EventHandler(this.OnPrevClick);
		this.NextBtn.Clicked += new global::System.EventHandler(this.OnNextClick);
	}
}
